// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArchiveChip: typeof import('./src/components/chip/ArchiveChip.vue')['default']
    AtBox: typeof import('./src/components/box/AtBox.vue')['default']
    AvatarBox: typeof import('./src/components/Menu/Avatar.vue')['default']
    Body: typeof import('./src/components/PostZone/Body.vue')['default']
    CoBox: typeof import('./src/components/Menu/About.vue')['default']
    CommentBox: typeof import('./src/components/box/CommentBox.vue')['default']
    CommentCard: typeof import('./src/components/CommentZone/CommentCard.vue')['default']
    CommentChip: typeof import('./src/components/chip/CommentCountChip.vue')['default']
    CommentEditor: typeof import('./src/components/CommentZone/CommentEditor.vue')['default']
    CommentList: typeof import('./src/components/CommentZone/CommentList.vue')['default']
    CreateTimeChip: typeof import('./src/components/chip/CreateTimeChip.vue')['default']
    DetailCard: typeof import('./src/components/PostZone/PostCard.vue')['default']
    FSlider: typeof import('./src/components/field/f-slider.vue')['default']
    GoUpBtn: typeof import('./src/components/btn/GoUpBtn.vue')['default']
    LockingTip: typeof import('./src/components/tip/LockingTip.vue')['default']
    ModifyTimeChip: typeof import('./src/components/chip/ModifyTimeChip.vue')['default']
    NavCol: typeof import('./src/components/col/NavCol.vue')['default']
    NaviColumn: typeof import('./src/components/Menu/Menu.vue')['default']
    NaviLine: typeof import('./src/components/MenuBar/MenuBar.vue')['default']
    NoCommentTip: typeof import('./src/components/tip/NoCommentTip.vue')['default']
    NoneBodyPreview: typeof import('./src/components/PostZone/NoneBodyPreview.vue')['default']
    NoteCard: typeof import('./src/components/PostZone/NoteCard.vue')['default']
    PageFoot: typeof import('./src/components/common/PageFoot.vue')['default']
    PageList: typeof import('./src/components/Menu/PageList.vue')['default']
    PageListCard: typeof import('./src/components/Menu/PageListCard.vue')['default']
    PostCard: typeof import('./src/components/card/PostCard.vue')['default']
    PostColumn: typeof import('./src/components/PostZone/PostZone.vue')['default']
    PostPreviewCard: typeof import('./src/components/card/PostPreviewCard.vue')['default']
    Preview: typeof import('./src/components/PostZone/Preview.vue')['default']
    PreviewCard: typeof import('./src/components/PostZone/PreviewCard.vue')['default']
    ReadTimeTip: typeof import('./src/components/PostZone/ReadTimeBar.vue')['default']
    ScheduleChip: typeof import('./src/components/chip/ScheduleChip.vue')['default']
    SiderBtn: typeof import('./src/components/MenuBar/SiderBtn.vue')['default']
    SiderList: typeof import('./src/components/MenuBar/Drawer.vue')['default']
    SiderListCard: typeof import('./src/components/MenuBar/SiderListCard.vue')['default']
    SwitchBtn: typeof import('./src/components/btn/SwitchZone.vue')['default']
    TopicChip: typeof import('./src/components/chip/TopicChip.vue')['default']
    UpBtn: typeof import('./src/components/btn/UpBtn.vue')['default']
    WarningTip: typeof import('./src/components/tip/WarningTip.vue')['default']
  }
}
