// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArchiveChip: typeof import('./src/components/tip/ArchiveChip.vue')['default']
    AtBox: typeof import('./src/components/box/AtBox.vue')['default']
    AvatarBox: typeof import('./src/components/NaviColumn/AvatarBox.vue')['default']
    Body: typeof import('./src/components/PostColumn/Body.vue')['default']
    CoBox: typeof import('./src/components/NaviColumn/CoBox.vue')['default']
    CommentBox: typeof import('./src/components/box/CommentBox.vue')['default']
    CommentCard: typeof import('./src/components/CommentList/CommentCard.vue')['default']
    CommentChip: typeof import('./src/components/tip/CommentChip.vue')['default']
    CommentEditor: typeof import('./src/components/CommentList/CommentEditor.vue')['default']
    CommentList: typeof import('./src/components/CommentList/CommentList.vue')['default']
    CreateTimeChip: typeof import('./src/components/PostColumn/CreateTimeChip.vue')['default']
    DetailCard: typeof import('./src/components/PostColumn/DetailCard.vue')['default']
    FSlider: typeof import('./src/components/field/f-slider.vue')['default']
    GoUpBtn: typeof import('./src/components/btn/GoUpBtn.vue')['default']
    LockingTip: typeof import('./src/components/tip/LockingTip.vue')['default']
    ModifyTimeChip: typeof import('./src/components/PostColumn/ModifyTimeChip.vue')['default']
    NavCol: typeof import('./src/components/col/NavCol.vue')['default']
    NaviColumn: typeof import('./src/components/NaviColumn/NaviColumn.vue')['default']
    NaviLine: typeof import('./src/components/NaviLine/NaviLine.vue')['default']
    NoCommentTip: typeof import('./src/components/tip/NoCommentTip.vue')['default']
    NoneBodyPreview: typeof import('./src/components/PostColumn/NoneBodyPreview.vue')['default']
    NoteCard: typeof import('./src/components/PostColumn/NoteCard.vue')['default']
    PageFoot: typeof import('./src/components/common/PageFoot.vue')['default']
    PageList: typeof import('./src/components/NaviColumn/PageList.vue')['default']
    PageListCard: typeof import('./src/components/NaviColumn/PageListCard.vue')['default']
    PostCard: typeof import('./src/components/card/PostCard.vue')['default']
    PostColumn: typeof import('./src/components/PostColumn/PostColumn.vue')['default']
    PostPreviewCard: typeof import('./src/components/card/PostPreviewCard.vue')['default']
    Preview: typeof import('./src/components/PostColumn/Preview.vue')['default']
    PreviewCard: typeof import('./src/components/PostColumn/PreviewCard.vue')['default']
    ReadTimeTip: typeof import('./src/components/tip/ReadTimeTip.vue')['default']
    ScheduleChip: typeof import('./src/components/tip/ScheduleChip.vue')['default']
    SiderBtn: typeof import('./src/components/NaviLine/SiderBtn.vue')['default']
    SiderList: typeof import('./src/components/NaviLine/SiderList.vue')['default']
    SiderListCard: typeof import('./src/components/NaviLine/SiderListCard.vue')['default']
    SwitchBtn: typeof import('./src/components/btn/SwitchBtn.vue')['default']
    TopicChip: typeof import('./src/components/PostColumn/TopicChip.vue')['default']
    UpBtn: typeof import('./src/components/btn/UpBtn.vue')['default']
    WarningTip: typeof import('./src/components/tip/WarningTip.vue')['default']
  }
}
